---
language: node_js

node_js:
 - "stable"

cache:
  directories:
  - node_modules
  - packages/*/node_modules

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_script:
  - npm run bootstrap

after_failure:
  - npm run debug
