---
language: node_js

node_js:
 - "stable"

cache:
  directories:
  - node_modules
  - packages/babel-plugin-react-server/node_modules
  - packages/babel-preset-react-server/node_modules
  - packages/generator-react-server/node_modules
  - packages/react-server/node_modules
  - packages/react-server-cli/node_modules
  - packages/react-server-core-middleware/node_modules
  - packages/react-server-data-bundle-cache/node_modules
  - packages/react-server-examples/node_modules
  - packages/react-server-gulp-module-tagger/node_modules
  - packages/react-server-integration-tests/node_modules
  - packages/react-server-module-tagger/node_modules
  - packages/react-server-test-pages/node_modules
  - packages/react-server-website/node_modules

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_script:
  - npm run bootstrap-no-i

after_failure:
  - npm run debug
