- name: Launch instances
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: Provision a set of instances
      ec2:
         key_name: walkscore_base_keypair2
         group: react-server
         instance_type: t2.nano
         image: ami-d732f0b7
         region: us-west-2
         vpc_subnet_id: subnet-d94db0ae
         assign_public_ip: yes
         instance_profile_name: react-server-box
         wait: yes
         exact_count: 1
         count_tag:
            Name: react-server-box
         instance_tags:
            Name: react-server-box
      register: ec2

    - name: Add all instance public IPs to host group
      add_host: hostname={{ item.public_ip }} groups=react-server-box-hosts
      with_items: '{{ ec2.instances }}'

    - name: Wait for SSH to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=30 timeout=320 state=started
      with_items: '{{ ec2.instances }}'

- name: Configuration
  hosts: react-server-box-hosts
  user: ubuntu

  tasks:
    - name: Set up Docker
      script: docker-setup.sh
